// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO activity_logs(behavior,module,entity_id,user_id,actor_id_snapshot,before,after,request_id,endpoint_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertAuditParams struct {
	Behavior        string         `json:"behavior"`
	Module          string         `json:"module"`
	EntityID        sql.NullString `json:"entity_id"`
	UserID          *string        `json:"user_id"`
	ActorIDSnapshot sql.NullString `json:"actor_id_snapshot"`
	Before          []byte         `json:"before"`
	After           []byte         `json:"after"`
	RequestID       sql.NullString `json:"request_id"`
	EndpointID      sql.NullString `json:"endpoint_id"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.Behavior,
		arg.Module,
		arg.EntityID,
		arg.UserID,
		arg.ActorIDSnapshot,
		arg.Before,
		arg.After,
		arg.RequestID,
		arg.EndpointID,
	)
	return err
}
