// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
)

const findActiveUserByEmail = `-- name: FindActiveUserByEmail :one
SELECT id, email, password, role_id, deleted_at, created_at, updated_at
FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) FindActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveUserByID = `-- name: FindActiveUserByID :one
SELECT id, email, password, role_id, deleted_at, created_at, updated_at
FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindActiveUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS (
  SELECT 1 FROM users u
  JOIN role_permissions rp ON rp.role_id = u.role_id
  JOIN permissions p ON p.id = rp.permission_id
  WHERE u.id = $1 AND u.deleted_at IS NULL AND p.name = $2
)
`

type UserHasPermissionParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPermission, arg.ID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
