// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimEmail = `-- name: ClaimEmail :exec
UPDATE email_jobs SET status='PROCESSING',attempts=attempts+1,lease_id=$1,lease_until=$2 WHERE id=$3
`

type ClaimEmailParams struct {
	LeaseID    *string      `json:"lease_id"`
	LeaseUntil sql.NullTime `json:"lease_until"`
	ID         string       `json:"id"`
}

func (q *Queries) ClaimEmail(ctx context.Context, arg ClaimEmailParams) error {
	_, err := q.db.Exec(ctx, claimEmail, arg.LeaseID, arg.LeaseUntil, arg.ID)
	return err
}

const claimableEmail = `-- name: ClaimableEmail :one
SELECT id, notification_id, recipient, title, body, status, attempts, available_at, lease_id, lease_until, completed_at, created_at FROM email_jobs WHERE (status='PENDING' AND available_at <= $1::timestamptz(3))
 OR (status='PROCESSING' AND lease_until <= $1::timestamptz(3))
 ORDER BY available_at,id LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimableEmail(ctx context.Context, now sql.NullTime) (EmailJob, error) {
	row := q.db.QueryRow(ctx, claimableEmail, now)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cleanupAudit = `-- name: CleanupAudit :many
SELECT id FROM activity_logs WHERE created_at < $1 ORDER BY id LIMIT $2::int FOR UPDATE SKIP LOCKED
`

type CleanupAuditParams struct {
	Cutoff    sql.NullTime `json:"cutoff"`
	BatchSize int32        `json:"batch_size"`
}

func (q *Queries) CleanupAudit(ctx context.Context, arg CleanupAuditParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cleanupAudit, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupEmail = `-- name: CleanupEmail :many
SELECT id FROM email_jobs WHERE status IN ('SENT','FAILED') AND completed_at < $1 ORDER BY id LIMIT $2::int FOR UPDATE SKIP LOCKED
`

type CleanupEmailParams struct {
	Cutoff    sql.NullTime `json:"cutoff"`
	BatchSize int32        `json:"batch_size"`
}

func (q *Queries) CleanupEmail(ctx context.Context, arg CleanupEmailParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cleanupEmail, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupFamilies = `-- name: CleanupFamilies :many
SELECT id FROM refresh_families WHERE revoked_at < $1 OR (revoked_at IS NULL AND expires_at < $1) ORDER BY id LIMIT $2::int FOR UPDATE SKIP LOCKED
`

type CleanupFamiliesParams struct {
	Cutoff    sql.NullTime `json:"cutoff"`
	BatchSize int32        `json:"batch_size"`
}

func (q *Queries) CleanupFamilies(ctx context.Context, arg CleanupFamiliesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cleanupFamilies, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeEmail = `-- name: CompleteEmail :exec
UPDATE email_jobs SET status=$1,available_at=$2,completed_at=$3,lease_id=NULL,lease_until=NULL WHERE id=$4
`

type CompleteEmailParams struct {
	Status      string       `json:"status"`
	AvailableAt sql.NullTime `json:"available_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          string       `json:"id"`
}

func (q *Queries) CompleteEmail(ctx context.Context, arg CompleteEmailParams) error {
	_, err := q.db.Exec(ctx, completeEmail,
		arg.Status,
		arg.AvailableAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const deleteAudit = `-- name: DeleteAudit :exec
DELETE FROM activity_logs WHERE id=$1
`

func (q *Queries) DeleteAudit(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAudit, id)
	return err
}

const deleteEmail = `-- name: DeleteEmail :exec
DELETE FROM email_jobs WHERE id=$1
`

func (q *Queries) DeleteEmail(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEmail, id)
	return err
}

const deleteFamily = `-- name: DeleteFamily :exec
DELETE FROM refresh_families WHERE id=$1
`

func (q *Queries) DeleteFamily(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFamily, id)
	return err
}

const emailBacklogCount = `-- name: EmailBacklogCount :one
SELECT count(*)::bigint FROM email_jobs WHERE status IN ('PENDING','PROCESSING')
`

func (q *Queries) EmailBacklogCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, emailBacklogCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const emailBacklogOldest = `-- name: EmailBacklogOldest :one
SELECT coalesce(min(created_at),now())::timestamptz FROM email_jobs WHERE status IN ('PENDING','PROCESSING')
`

func (q *Queries) EmailBacklogOldest(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRow(ctx, emailBacklogOldest)
	var column_1 sql.NullTime
	err := row.Scan(&column_1)
	return column_1, err
}

const enqueueEmail = `-- name: EnqueueEmail :exec
INSERT INTO email_jobs(id,notification_id,recipient,title,body) VALUES($1,$2,$3,$4,$5)
`

type EnqueueEmailParams struct {
	ID             string `json:"id"`
	NotificationID string `json:"notification_id"`
	Recipient      string `json:"recipient"`
	Title          string `json:"title"`
	Body           string `json:"body"`
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) error {
	_, err := q.db.Exec(ctx, enqueueEmail,
		arg.ID,
		arg.NotificationID,
		arg.Recipient,
		arg.Title,
		arg.Body,
	)
	return err
}

const lockEmail = `-- name: LockEmail :one
SELECT id, notification_id, recipient, title, body, status, attempts, available_at, lease_id, lease_until, completed_at, created_at FROM email_jobs WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockEmail(ctx context.Context, id string) (EmailJob, error) {
	row := q.db.QueryRow(ctx, lockEmail, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const renewEmail = `-- name: RenewEmail :execrows
UPDATE email_jobs SET lease_until=$1 WHERE id=$2 AND lease_id=$3 AND status='PROCESSING' AND lease_until > now()
`

type RenewEmailParams struct {
	LeaseUntil sql.NullTime `json:"lease_until"`
	ID         string       `json:"id"`
	LeaseID    *string      `json:"lease_id"`
}

func (q *Queries) RenewEmail(ctx context.Context, arg RenewEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewEmail, arg.LeaseUntil, arg.ID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
