// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package sqlc

import (
	"context"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions(name) VALUES($1) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePermission(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, name)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id=$1
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const findPermission = `-- name: FindPermission :one
SELECT id, name, created_at, updated_at FROM permissions WHERE id=$1
`

func (q *Queries) FindPermission(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRow(ctx, findPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, created_at, updated_at FROM permissions ORDER BY name,id
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPermission = `-- name: LockPermission :one
SELECT id, name, created_at, updated_at FROM permissions WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockPermission(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRow(ctx, lockPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions SET name=$2,updated_at=now() WHERE id=$1 RETURNING id, name, created_at, updated_at
`

type UpdatePermissionParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission, arg.ID, arg.Name)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
