// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlc

import (
	"context"
)

const seedAdminPermissions = `-- name: SeedAdminPermissions :exec
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='admin' ON CONFLICT DO NOTHING
`

func (q *Queries) SeedAdminPermissions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedAdminPermissions)
	return err
}

const seedPermission = `-- name: SeedPermission :exec
INSERT INTO permissions(name) VALUES($1) ON CONFLICT(name) DO NOTHING
`

func (q *Queries) SeedPermission(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, seedPermission, name)
	return err
}

const seedRole = `-- name: SeedRole :exec
INSERT INTO roles(name) VALUES($1) ON CONFLICT(name) DO NOTHING
`

func (q *Queries) SeedRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, seedRole, name)
	return err
}

const seedUser = `-- name: SeedUser :exec
INSERT INTO users(email,password,role_id) SELECT lower($1),$2,id FROM roles WHERE name=$3 ON CONFLICT(email) DO UPDATE SET role_id=EXCLUDED.role_id,deleted_at=NULL,updated_at=now()
`

type SeedUserParams struct {
	Lower    string `json:"lower"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

func (q *Queries) SeedUser(ctx context.Context, arg SeedUserParams) error {
	_, err := q.db.Exec(ctx, seedUser, arg.Lower, arg.Password, arg.Name)
	return err
}
