// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL AND ($1::text='' OR email ILIKE '%'||$1::text||'%')
`

func (q *Queries) CountUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(email,password,role_id) VALUES(lower($1),$2,$3) RETURNING id, email, password, role_id, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Lower    string `json:"lower"`
	Password string `json:"password"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Lower, arg.Password, arg.RoleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT id, email, password, role_id, deleted_at, created_at, updated_at FROM users WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) FindUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, role_id, deleted_at, created_at, updated_at FROM users WHERE deleted_at IS NULL AND ($1::text='' OR email ILIKE '%'||$1::text||'%')
ORDER BY
 CASE WHEN $2::text='email' AND $3::text='asc' THEN email END ASC,
 CASE WHEN $2::text='email' AND $3::text='desc' THEN email END DESC,
 CASE WHEN $2::text='createdAt' AND $3::text='asc' THEN created_at END ASC,
 CASE WHEN $2::text='createdAt' AND $3::text='desc' THEN created_at END DESC,
 CASE WHEN $2::text='updatedAt' AND $3::text='asc' THEN updated_at END ASC,
 CASE WHEN $2::text='updatedAt' AND $3::text='desc' THEN updated_at END DESC,
 id ASC LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Search     string `json:"search"`
	SortBy     string `json:"sort_by"`
	Direction  string `json:"direction"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.SortBy,
		arg.Direction,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.RoleID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id, email, password, role_id, deleted_at, created_at, updated_at FROM users WHERE id=$1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at=now(),updated_at=now() WHERE id=$1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET email=coalesce(lower($1::text),email),role_id=coalesce($2::uuid,role_id),updated_at=now() WHERE id=$3 RETURNING id, email, password, role_id, deleted_at, created_at, updated_at
`

type UpdateUserParams struct {
	Email  pgtype.Text `json:"email"`
	RoleID *string     `json:"role_id"`
	ID     string      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Email, arg.RoleID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
