// Generates a typed decorator from the authoritative sqlc port. Run after sqlc generate.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"strings"
)

func main() {
	fs := token.NewFileSet()
	file, err := parser.ParseFile(fs, "internal/db/sqlc/querier.go", nil, 0)
	must(err)
	var port *ast.InterfaceType
	ast.Inspect(file, func(node ast.Node) bool {
		spec, ok := node.(*ast.TypeSpec)
		if ok && spec.Name.Name == "Querier" {
			port = spec.Type.(*ast.InterfaceType)
		}
		return true
	})
	if port == nil {
		panic("sqlc Querier missing")
	}
	render := func(node ast.Node) string {
		var out bytes.Buffer
		must(printer.Fprint(&out, fs, node))
		return out.String()
	}
	var out strings.Builder
	out.WriteString("// Code generated by cmd/generate-db-instrumentation. DO NOT EDIT.\npackage db\nimport(\"context\";\"database/sql\";\"github.com/RidhuanDEV/golang-backend/internal/db/sqlc\";\"github.com/RidhuanDEV/golang-backend/internal/telemetry\")\ntype tracedQueries struct{q sqlc.Querier}\nvar _ sqlc.Querier=(*tracedQueries)(nil)\n")
	for _, method := range port.Methods.List {
		name := method.Names[0].Name
		fn := method.Type.(*ast.FuncType)
		qualify := func(expr ast.Expr) string {
			value := render(expr)
			if _, ok := expr.(*ast.Ident); ok && value != "error" && value != "string" && value != "bool" && value != "int64" {
				return "sqlc." + value
			}
			if list, ok := expr.(*ast.ArrayType); ok {
				if id, ok := list.Elt.(*ast.Ident); ok && id.Name != "string" && id.Name != "byte" {
					return "[]sqlc." + id.Name
				}
			}
			return value
		}
		params, calls, returns, names := []string{}, []string{}, []string{}, []string{}
		for _, field := range fn.Params.List {
			for _, param := range field.Names {
				params = append(params, param.Name+" "+qualify(field.Type))
				calls = append(calls, param.Name)
			}
		}
		for i, field := range fn.Results.List {
			returns = append(returns, qualify(field.Type))
			names = append(names, fmt.Sprintf("r%d", i))
		}
		fmt.Fprintf(&out, "func(t *tracedQueries)%s(%s)(%s){ctx,span:=telemetry.Start(ctx,\"database\");%s:=t.q.%s(%s);telemetry.Finish(span,%s);return %s}\n", name, strings.Join(params, ","), strings.Join(returns, ","), strings.Join(names, ","), name, strings.Join(calls, ","), names[len(names)-1], strings.Join(names, ","))
	}
	source, err := format.Source([]byte(out.String()))
	must(err)
	must(os.WriteFile("internal/db/telemetry_queries.go", source, 0644))
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
