// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO activity_logs(behavior,module,entity_id,user_id,actor_id_snapshot,` + "`" + `before` + "`" + `,` + "`" + `after` + "`" + `,request_id,endpoint_id) VALUES(?,?,?,?,?,?,?,?,?)
`

type InsertAuditParams struct {
	Behavior        string          `json:"behavior"`
	Module          string          `json:"module"`
	EntityID        sql.NullString  `json:"entity_id"`
	UserID          *string         `json:"user_id"`
	ActorIDSnapshot sql.NullString  `json:"actor_id_snapshot"`
	Before          json.RawMessage `json:"before"`
	After           json.RawMessage `json:"after"`
	RequestID       sql.NullString  `json:"request_id"`
	EndpointID      sql.NullString  `json:"endpoint_id"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.Behavior,
		arg.Module,
		arg.EntityID,
		arg.UserID,
		arg.ActorIDSnapshot,
		arg.Before,
		arg.After,
		arg.RequestID,
		arg.EndpointID,
	)
	return err
}
