// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
)

const advanceRefreshFamily = `-- name: AdvanceRefreshFamily :exec
UPDATE refresh_families SET expires_at=? WHERE id=?
`

type AdvanceRefreshFamilyParams struct {
	ExpiresAt sql.NullTime `json:"expires_at"`
	ID        string       `json:"id"`
}

func (q *Queries) AdvanceRefreshFamily(ctx context.Context, arg AdvanceRefreshFamilyParams) error {
	_, err := q.db.ExecContext(ctx, advanceRefreshFamily, arg.ExpiresAt, arg.ID)
	return err
}

const createAuthRefreshToken = `-- name: CreateAuthRefreshToken :exec
INSERT INTO auth_refresh_tokens(family_id,user_id,token_hash,expires_at) VALUES(?,?,?,?)
`

type CreateAuthRefreshTokenParams struct {
	FamilyID  string       `json:"family_id"`
	UserID    string       `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAuthRefreshToken(ctx context.Context, arg CreateAuthRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthRefreshToken,
		arg.FamilyID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshFamily = `-- name: CreateRefreshFamily :exec
INSERT INTO refresh_families(id,user_id,expires_at) VALUES(?,?,?)
`

type CreateRefreshFamilyParams struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateRefreshFamily(ctx context.Context, arg CreateRefreshFamilyParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshFamily, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredAuthRefreshTokens = `-- name: DeleteExpiredAuthRefreshTokens :exec
DELETE FROM auth_refresh_tokens WHERE user_id=? AND expires_at<CURRENT_TIMESTAMP(3)
`

func (q *Queries) DeleteExpiredAuthRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthRefreshTokens, userID)
	return err
}

const findActiveUserByEmail = `-- name: FindActiveUserByEmail :one
SELECT id,email,password,role_id,deleted_at,created_at,updated_at FROM users WHERE email=? AND deleted_at IS NULL
`

func (q *Queries) FindActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveUserByID = `-- name: FindActiveUserByID :one
SELECT id,email,password,role_id,deleted_at,created_at,updated_at FROM users WHERE id=? AND deleted_at IS NULL
`

func (q *Queries) FindActiveUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAuthRefreshTokenByHash = `-- name: FindAuthRefreshTokenByHash :one
SELECT id,family_id,user_id,token_hash,expires_at,created_at,revoked_at FROM auth_refresh_tokens WHERE token_hash=? FOR UPDATE
`

func (q *Queries) FindAuthRefreshTokenByHash(ctx context.Context, tokenHash []byte) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findAuthRefreshTokenByHash, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockRefreshFamily = `-- name: LockRefreshFamily :one
SELECT id, user_id, created_at, expires_at, revoked_at FROM refresh_families WHERE id=? FOR UPDATE
`

func (q *Queries) LockRefreshFamily(ctx context.Context, id string) (RefreshFamily, error) {
	row := q.db.QueryRowContext(ctx, lockRefreshFamily, id)
	var i RefreshFamily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const lookupAuthRefreshToken = `-- name: LookupAuthRefreshToken :one
SELECT id, family_id, user_id, token_hash, expires_at, created_at, revoked_at FROM auth_refresh_tokens WHERE token_hash=?
`

func (q *Queries) LookupAuthRefreshToken(ctx context.Context, tokenHash []byte) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, lookupAuthRefreshToken, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAuthRefreshFamily = `-- name: RevokeAuthRefreshFamily :exec
UPDATE auth_refresh_tokens SET revoked_at=CURRENT_TIMESTAMP(3) WHERE family_id=? AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthRefreshFamily(ctx context.Context, familyID string) error {
	_, err := q.db.ExecContext(ctx, revokeAuthRefreshFamily, familyID)
	return err
}

const revokeAuthRefreshToken = `-- name: RevokeAuthRefreshToken :execrows
UPDATE auth_refresh_tokens SET revoked_at=CURRENT_TIMESTAMP(3) WHERE id=? AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthRefreshToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAuthRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeRefreshFamilyRecord = `-- name: RevokeRefreshFamilyRecord :exec
UPDATE refresh_families SET revoked_at=COALESCE(revoked_at,CURRENT_TIMESTAMP(3)) WHERE id=?
`

func (q *Queries) RevokeRefreshFamilyRecord(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshFamilyRecord, id)
	return err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS(SELECT 1 FROM users u JOIN role_permissions rp ON rp.role_id=u.role_id JOIN permissions p ON p.id=rp.permission_id WHERE u.id=? AND u.deleted_at IS NULL AND p.name=?)
`

type UserHasPermissionParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasPermission, arg.ID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
