// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
)

const claimEmail = `-- name: ClaimEmail :exec
UPDATE email_jobs SET status='PROCESSING',attempts=attempts+1,lease_id=?,lease_until=? WHERE id=?
`

type ClaimEmailParams struct {
	LeaseID    *string      `json:"lease_id"`
	LeaseUntil sql.NullTime `json:"lease_until"`
	ID         string       `json:"id"`
}

func (q *Queries) ClaimEmail(ctx context.Context, arg ClaimEmailParams) error {
	_, err := q.db.ExecContext(ctx, claimEmail, arg.LeaseID, arg.LeaseUntil, arg.ID)
	return err
}

const claimableEmail = `-- name: ClaimableEmail :one
SELECT id, notification_id, recipient, title, body, status, attempts, available_at, lease_id, lease_until, completed_at, created_at FROM email_jobs WHERE (status='PENDING' AND available_at <= ?)
 OR (status='PROCESSING' AND lease_until <= ?)
 ORDER BY available_at,id LIMIT 1 FOR UPDATE SKIP LOCKED
`

type ClaimableEmailParams struct {
	Now sql.NullTime `json:"now"`
}

func (q *Queries) ClaimableEmail(ctx context.Context, arg ClaimableEmailParams) (EmailJob, error) {
	row := q.db.QueryRowContext(ctx, claimableEmail, arg.Now, arg.Now)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cleanupAudit = `-- name: CleanupAudit :many
SELECT id FROM activity_logs WHERE created_at < ? ORDER BY id LIMIT ? FOR UPDATE SKIP LOCKED
`

type CleanupAuditParams struct {
	Cutoff sql.NullTime `json:"cutoff"`
	Limit  int32        `json:"limit"`
}

func (q *Queries) CleanupAudit(ctx context.Context, arg CleanupAuditParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, cleanupAudit, arg.Cutoff, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupEmail = `-- name: CleanupEmail :many
SELECT id FROM email_jobs WHERE status IN ('SENT','FAILED') AND completed_at < ? ORDER BY id LIMIT ? FOR UPDATE SKIP LOCKED
`

type CleanupEmailParams struct {
	Cutoff sql.NullTime `json:"cutoff"`
	Limit  int32        `json:"limit"`
}

func (q *Queries) CleanupEmail(ctx context.Context, arg CleanupEmailParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, cleanupEmail, arg.Cutoff, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupFamilies = `-- name: CleanupFamilies :many
SELECT id FROM refresh_families WHERE revoked_at < ? OR (revoked_at IS NULL AND expires_at < ?) ORDER BY id LIMIT ? FOR UPDATE SKIP LOCKED
`

type CleanupFamiliesParams struct {
	Cutoff sql.NullTime `json:"cutoff"`
	Limit  int32        `json:"limit"`
}

func (q *Queries) CleanupFamilies(ctx context.Context, arg CleanupFamiliesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, cleanupFamilies, arg.Cutoff, arg.Cutoff, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeEmail = `-- name: CompleteEmail :exec
UPDATE email_jobs SET status=?,available_at=?,completed_at=?,lease_id=NULL,lease_until=NULL WHERE id=?
`

type CompleteEmailParams struct {
	Status      string       `json:"status"`
	AvailableAt sql.NullTime `json:"available_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          string       `json:"id"`
}

func (q *Queries) CompleteEmail(ctx context.Context, arg CompleteEmailParams) error {
	_, err := q.db.ExecContext(ctx, completeEmail,
		arg.Status,
		arg.AvailableAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const deleteAudit = `-- name: DeleteAudit :exec
DELETE FROM activity_logs WHERE id=?
`

func (q *Queries) DeleteAudit(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAudit, id)
	return err
}

const deleteEmail = `-- name: DeleteEmail :exec
DELETE FROM email_jobs WHERE id=?
`

func (q *Queries) DeleteEmail(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEmail, id)
	return err
}

const deleteFamily = `-- name: DeleteFamily :exec
DELETE FROM refresh_families WHERE id=?
`

func (q *Queries) DeleteFamily(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFamily, id)
	return err
}

const emailBacklogCount = `-- name: EmailBacklogCount :one
SELECT count(*) FROM email_jobs WHERE status IN ('PENDING','PROCESSING')
`

func (q *Queries) EmailBacklogCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, emailBacklogCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const emailBacklogOldest = `-- name: EmailBacklogOldest :one
SELECT CAST(COALESCE(MIN(created_at),CURRENT_TIMESTAMP(3)) AS DATETIME) FROM email_jobs WHERE status IN ('PENDING','PROCESSING')
`

func (q *Queries) EmailBacklogOldest(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, emailBacklogOldest)
	var column_1 sql.NullTime
	err := row.Scan(&column_1)
	return column_1, err
}

const enqueueEmail = `-- name: EnqueueEmail :exec
INSERT INTO email_jobs(id,notification_id,recipient,title,body) VALUES(?,?,?,?,?)
`

type EnqueueEmailParams struct {
	ID             string `json:"id"`
	NotificationID string `json:"notification_id"`
	Recipient      string `json:"recipient"`
	Title          string `json:"title"`
	Body           string `json:"body"`
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) error {
	_, err := q.db.ExecContext(ctx, enqueueEmail,
		arg.ID,
		arg.NotificationID,
		arg.Recipient,
		arg.Title,
		arg.Body,
	)
	return err
}

const lockEmail = `-- name: LockEmail :one
SELECT id, notification_id, recipient, title, body, status, attempts, available_at, lease_id, lease_until, completed_at, created_at FROM email_jobs WHERE id=? FOR UPDATE
`

func (q *Queries) LockEmail(ctx context.Context, id string) (EmailJob, error) {
	row := q.db.QueryRowContext(ctx, lockEmail, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const renewEmail = `-- name: RenewEmail :execrows
UPDATE email_jobs SET lease_until=? WHERE id=? AND lease_id=? AND status='PROCESSING' AND lease_until > CURRENT_TIMESTAMP(3)
`

type RenewEmailParams struct {
	LeaseUntil sql.NullTime `json:"lease_until"`
	ID         string       `json:"id"`
	LeaseID    *string      `json:"lease_id"`
}

func (q *Queries) RenewEmail(ctx context.Context, arg RenewEmailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewEmail, arg.LeaseUntil, arg.ID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
