// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysqlsqlc

import (
	"database/sql"
	"encoding/json"
)

type ActivityLog struct {
	ID              string          `json:"id"`
	Behavior        string          `json:"behavior"`
	Module          string          `json:"module"`
	EntityID        sql.NullString  `json:"entity_id"`
	UserID          *string         `json:"user_id"`
	ActorIDSnapshot sql.NullString  `json:"actor_id_snapshot"`
	Before          json.RawMessage `json:"before"`
	After           json.RawMessage `json:"after"`
	RequestID       sql.NullString  `json:"request_id"`
	EndpointID      sql.NullString  `json:"endpoint_id"`
	CreatedAt       sql.NullTime    `json:"created_at"`
}

type AuthRefreshToken struct {
	ID        string       `json:"id"`
	FamilyID  string       `json:"family_id"`
	UserID    string       `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type EmailJob struct {
	ID             string       `json:"id"`
	NotificationID string       `json:"notification_id"`
	Recipient      string       `json:"recipient"`
	Title          string       `json:"title"`
	Body           string       `json:"body"`
	Status         string       `json:"status"`
	Attempts       int32        `json:"attempts"`
	AvailableAt    sql.NullTime `json:"available_at"`
	LeaseID        *string      `json:"lease_id"`
	LeaseUntil     sql.NullTime `json:"lease_until"`
	CompletedAt    sql.NullTime `json:"completed_at"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Notification struct {
	ID          string       `json:"id"`
	RecipientID string       `json:"recipient_id"`
	ActorID     *string      `json:"actor_id"`
	Title       string       `json:"title"`
	Body        string       `json:"body"`
	EmailStatus string       `json:"email_status"`
	ReadAt      sql.NullTime `json:"read_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
	Sequence    int64        `json:"sequence"`
}

type NotificationCounter struct {
	RecipientID string `json:"recipient_id"`
	Sequence    int64  `json:"sequence"`
}

type Permission struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type RefreshFamily struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type StoredFile struct {
	ID           string       `json:"id"`
	Storage      string       `json:"storage"`
	Status       string       `json:"status"`
	ObjectKey    string       `json:"object_key"`
	OriginalName string       `json:"original_name"`
	MimeType     string       `json:"mime_type"`
	Size         int64        `json:"size"`
	UploaderID   *string      `json:"uploader_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type User struct {
	ID        string       `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	RoleID    string       `json:"role_id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
