// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package mysqlsqlc

import (
	"context"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications(id,recipient_id,actor_id,title,body,email_status) VALUES(?,?,?,?,?,?)
`

type CreateNotificationParams struct {
	ID          string  `json:"id"`
	RecipientID string  `json:"recipient_id"`
	ActorID     *string `json:"actor_id"`
	Title       string  `json:"title"`
	Body        string  `json:"body"`
	EmailStatus string  `json:"email_status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.RecipientID,
		arg.ActorID,
		arg.Title,
		arg.Body,
		arg.EmailStatus,
	)
	return err
}

const findNotification = `-- name: FindNotification :one
SELECT id, recipient_id, actor_id, title, body, email_status, read_at, created_at FROM notifications WHERE id=?
`

func (q *Queries) FindNotification(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, findNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Title,
		&i.Body,
		&i.EmailStatus,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnNotifications = `-- name: ListOwnNotifications :many
SELECT id, recipient_id, actor_id, title, body, email_status, read_at, created_at FROM notifications WHERE recipient_id=? AND (CAST(? AS SIGNED)=0 OR read_at IS NULL) ORDER BY created_at DESC,id DESC LIMIT 50
`

type ListOwnNotificationsParams struct {
	RecipientID string `json:"recipient_id"`
	Unread      int64  `json:"unread"`
}

func (q *Queries) ListOwnNotifications(ctx context.Context, arg ListOwnNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listOwnNotifications, arg.RecipientID, arg.Unread)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.Title,
			&i.Body,
			&i.EmailStatus,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnNotification = `-- name: LockOwnNotification :one
SELECT id, recipient_id, actor_id, title, body, email_status, read_at, created_at FROM notifications WHERE id=? AND recipient_id=? FOR UPDATE
`

type LockOwnNotificationParams struct {
	ID          string `json:"id"`
	RecipientID string `json:"recipient_id"`
}

func (q *Queries) LockOwnNotification(ctx context.Context, arg LockOwnNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, lockOwnNotification, arg.ID, arg.RecipientID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Title,
		&i.Body,
		&i.EmailStatus,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const readNotification = `-- name: ReadNotification :exec
UPDATE notifications SET read_at=coalesce(read_at,CURRENT_TIMESTAMP(3)) WHERE id=?
`

func (q *Queries) ReadNotification(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, readNotification, id)
	return err
}

const setNotificationEmailStatus = `-- name: SetNotificationEmailStatus :exec
UPDATE notifications SET email_status=? WHERE id=?
`

type SetNotificationEmailStatusParams struct {
	EmailStatus string `json:"email_status"`
	ID          string `json:"id"`
}

func (q *Queries) SetNotificationEmailStatus(ctx context.Context, arg SetNotificationEmailStatusParams) error {
	_, err := q.db.ExecContext(ctx, setNotificationEmailStatus, arg.EmailStatus, arg.ID)
	return err
}
