// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package mysqlsqlc

import (
	"context"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions(id,name) VALUES(?,?)
`

type CreatePermissionParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission, arg.ID, arg.Name)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id=?
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const findPermission = `-- name: FindPermission :one
SELECT id, name, created_at, updated_at FROM permissions WHERE id=?
`

func (q *Queries) FindPermission(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, findPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, created_at, updated_at FROM permissions ORDER BY name,id
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPermission = `-- name: LockPermission :one
SELECT id, name, created_at, updated_at FROM permissions WHERE id=? FOR UPDATE
`

func (q *Queries) LockPermission(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, lockPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions SET name=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?
`

type UpdatePermissionParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission, arg.Name, arg.ID)
	return err
}
