// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package mysqlsqlc

import (
	"context"
)

const assignRolePermission = `-- name: AssignRolePermission :exec
INSERT INTO role_permissions(role_id,permission_id) VALUES(?,?) ON DUPLICATE KEY UPDATE permission_id=permission_id
`

type AssignRolePermissionParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) AssignRolePermission(ctx context.Context, arg AssignRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, assignRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id=?
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.ExecContext(ctx, clearRolePermissions, roleID)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles(id,name) VALUES(?,?)
`

type CreateRoleParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.ID, arg.Name)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id=?
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const findRole = `-- name: FindRole :one
SELECT id, name, created_at, updated_at FROM roles WHERE id=?
`

func (q *Queries) FindRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRoleByName = `-- name: FindRoleByName :one
SELECT id, name, created_at, updated_at FROM roles WHERE name=?
`

func (q *Queries) FindRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolePermissionIDs = `-- name: ListRolePermissionIDs :many
SELECT permission_id FROM role_permissions WHERE role_id=? ORDER BY permission_id
`

func (q *Queries) ListRolePermissionIDs(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRolePermissionIDs, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_id string
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.id,p.name FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id WHERE rp.role_id=? ORDER BY p.name,p.id
`

type ListRolePermissionsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListRolePermissions(ctx context.Context, roleID string) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionsRow{}
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, created_at, updated_at FROM roles ORDER BY name,id
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRole = `-- name: LockRole :one
SELECT id, name, created_at, updated_at FROM roles WHERE id=? FOR UPDATE
`

func (q *Queries) LockRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, lockRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET name=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?
`

type UpdateRoleParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole, arg.Name, arg.ID)
	return err
}
