// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package mysqlsqlc

import (
	"context"
)

const seedAdminPermissions = `-- name: SeedAdminPermissions :exec
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='admin' ON DUPLICATE KEY UPDATE permission_id=permission_id
`

func (q *Queries) SeedAdminPermissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedAdminPermissions)
	return err
}

const seedPermission = `-- name: SeedPermission :exec
INSERT INTO permissions(name) VALUES(?) ON DUPLICATE KEY UPDATE name=name
`

func (q *Queries) SeedPermission(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, seedPermission, name)
	return err
}

const seedRole = `-- name: SeedRole :exec
INSERT INTO roles(name) VALUES(?) ON DUPLICATE KEY UPDATE name=name
`

func (q *Queries) SeedRole(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, seedRole, name)
	return err
}

const seedUser = `-- name: SeedUser :exec
INSERT INTO users(email,password,role_id) SELECT lower(?),?,id FROM roles WHERE name=? ON DUPLICATE KEY UPDATE role_id=VALUES(role_id),deleted_at=NULL,updated_at=CURRENT_TIMESTAMP(3)
`

type SeedUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

func (q *Queries) SeedUser(ctx context.Context, arg SeedUserParams) error {
	_, err := q.db.ExecContext(ctx, seedUser, arg.Email, arg.Password, arg.Name)
	return err
}
