// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload.sql

package mysqlsqlc

import (
	"context"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO stored_files(id,storage,object_key,original_name,mime_type,size,uploader_id) VALUES(?,?,?,?,?,?,?)
`

type CreateFileParams struct {
	ID           string  `json:"id"`
	Storage      string  `json:"storage"`
	ObjectKey    string  `json:"object_key"`
	OriginalName string  `json:"original_name"`
	MimeType     string  `json:"mime_type"`
	Size         int64   `json:"size"`
	UploaderID   *string `json:"uploader_id"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.Storage,
		arg.ObjectKey,
		arg.OriginalName,
		arg.MimeType,
		arg.Size,
		arg.UploaderID,
	)
	return err
}

const fileReferenced = `-- name: FileReferenced :one
SELECT EXISTS(SELECT 1 FROM stored_files WHERE object_key=? AND storage=?)
`

type FileReferencedParams struct {
	ObjectKey string `json:"object_key"`
	Storage   string `json:"storage"`
}

func (q *Queries) FileReferenced(ctx context.Context, arg FileReferencedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, fileReferenced, arg.ObjectKey, arg.Storage)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findFile = `-- name: FindFile :one
SELECT id, storage, status, object_key, original_name, mime_type, size, uploader_id, created_at FROM stored_files WHERE id=? AND status='READY'
`

func (q *Queries) FindFile(ctx context.Context, id string) (StoredFile, error) {
	row := q.db.QueryRowContext(ctx, findFile, id)
	var i StoredFile
	err := row.Scan(
		&i.ID,
		&i.Storage,
		&i.Status,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.UploaderID,
		&i.CreatedAt,
	)
	return i, err
}
