// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL AND (?='' OR lower(email) LIKE concat('%',lower(?),'%'))
`

type CountUsersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id,email,password,role_id) VALUES(?,lower(?),?,?)
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.RoleID,
	)
	return err
}

const findUser = `-- name: FindUser :one
SELECT id, email, password, role_id, deleted_at, created_at, updated_at FROM users WHERE id=? AND deleted_at IS NULL
`

func (q *Queries) FindUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, role_id, deleted_at, created_at, updated_at FROM users WHERE deleted_at IS NULL AND (?='' OR lower(email) LIKE concat('%',lower(?),'%'))
ORDER BY
 CASE WHEN CAST(? AS SIGNED)=1 AND CAST(? AS SIGNED)=0 THEN email END ASC,
 CASE WHEN CAST(? AS SIGNED)=1 AND CAST(? AS SIGNED)=1 THEN email END DESC,
 CASE WHEN CAST(? AS SIGNED)=2 AND CAST(? AS SIGNED)=0 THEN created_at END ASC,
 CASE WHEN CAST(? AS SIGNED)=2 AND CAST(? AS SIGNED)=1 THEN created_at END DESC,
 CASE WHEN CAST(? AS SIGNED)=3 AND CAST(? AS SIGNED)=0 THEN updated_at END ASC,
 CASE WHEN CAST(? AS SIGNED)=3 AND CAST(? AS SIGNED)=1 THEN updated_at END DESC,
 id ASC LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Search     string `json:"search"`
	SortKey    int64  `json:"sort_key"`
	Descending int64  `json:"descending"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Search,
		arg.Search,
		arg.SortKey,
		arg.Descending,
		arg.SortKey,
		arg.Descending,
		arg.SortKey,
		arg.Descending,
		arg.SortKey,
		arg.Descending,
		arg.SortKey,
		arg.Descending,
		arg.SortKey,
		arg.Descending,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.RoleID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id, email, password, role_id, deleted_at, created_at, updated_at FROM users WHERE id=? AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at=CURRENT_TIMESTAMP(3),updated_at=CURRENT_TIMESTAMP(3) WHERE id=?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET email=coalesce(lower(?),email),role_id=coalesce(?,role_id),updated_at=CURRENT_TIMESTAMP(3) WHERE id=?
`

type UpdateUserParams struct {
	Email  sql.NullString `json:"email"`
	RoleID sql.NullString `json:"role_id"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Email, arg.RoleID, arg.ID)
	return err
}
