// Code generated by cmd/generate-db-instrumentation. DO NOT EDIT.
package db

import (
	"context"
	"database/sql"
	"github.com/RidhuanDEV/golang-backend/internal/db/sqlc"
	"github.com/RidhuanDEV/golang-backend/internal/telemetry"
)

type tracedQueries struct{ q sqlc.Querier }

var _ sqlc.Querier = (*tracedQueries)(nil)

func (t *tracedQueries) AdvanceRefreshFamily(ctx context.Context, arg sqlc.AdvanceRefreshFamilyParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.AdvanceRefreshFamily(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) AssignRolePermission(ctx context.Context, arg sqlc.AssignRolePermissionParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.AssignRolePermission(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) ClaimEmail(ctx context.Context, arg sqlc.ClaimEmailParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.ClaimEmail(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) ClaimableEmail(ctx context.Context, now sql.NullTime) (sqlc.EmailJob, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ClaimableEmail(ctx, now)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CleanupAudit(ctx context.Context, arg sqlc.CleanupAuditParams) ([]string, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CleanupAudit(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CleanupEmail(ctx context.Context, arg sqlc.CleanupEmailParams) ([]string, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CleanupEmail(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CleanupFamilies(ctx context.Context, arg sqlc.CleanupFamiliesParams) ([]string, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CleanupFamilies(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ClearRolePermissions(ctx context.Context, roleID string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.ClearRolePermissions(ctx, roleID)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) CompleteEmail(ctx context.Context, arg sqlc.CompleteEmailParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.CompleteEmail(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) CountUsers(ctx context.Context, search string) (int64, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CountUsers(ctx, search)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CreateAuthRefreshToken(ctx context.Context, arg sqlc.CreateAuthRefreshTokenParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.CreateAuthRefreshToken(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) CreateFile(ctx context.Context, arg sqlc.CreateFileParams) (sqlc.StoredFile, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CreateFile(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CreateNotification(ctx context.Context, arg sqlc.CreateNotificationParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.CreateNotification(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) CreatePermission(ctx context.Context, name string) (sqlc.Permission, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CreatePermission(ctx, name)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CreateRefreshFamily(ctx context.Context, arg sqlc.CreateRefreshFamilyParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.CreateRefreshFamily(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) CreateRole(ctx context.Context, name string) (sqlc.Role, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CreateRole(ctx, name)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.CreateUser(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) DeleteAudit(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.DeleteAudit(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) DeleteEmail(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.DeleteEmail(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) DeleteExpiredAuthRefreshTokens(ctx context.Context, userID string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.DeleteExpiredAuthRefreshTokens(ctx, userID)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) DeleteFamily(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.DeleteFamily(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) DeletePermission(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.DeletePermission(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) DeleteRole(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.DeleteRole(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) EmailBacklogCount(ctx context.Context) (int64, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.EmailBacklogCount(ctx)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) EmailBacklogOldest(ctx context.Context) (sql.NullTime, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.EmailBacklogOldest(ctx)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) EnqueueEmail(ctx context.Context, arg sqlc.EnqueueEmailParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.EnqueueEmail(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) EnsureNotificationCounter(ctx context.Context, recipientID string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.EnsureNotificationCounter(ctx, recipientID)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) FileReferenced(ctx context.Context, arg sqlc.FileReferencedParams) (bool, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FileReferenced(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindActiveUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindActiveUserByEmail(ctx, email)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindActiveUserByID(ctx context.Context, id string) (sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindActiveUserByID(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindAuthRefreshTokenByHash(ctx context.Context, tokenHash []byte) (sqlc.AuthRefreshToken, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindAuthRefreshTokenByHash(ctx, tokenHash)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindFile(ctx context.Context, id string) (sqlc.StoredFile, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindFile(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindNotification(ctx context.Context, id string) (sqlc.Notification, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindNotification(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindPermission(ctx context.Context, id string) (sqlc.Permission, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindPermission(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindRole(ctx context.Context, id string) (sqlc.Role, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindRole(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindRoleByName(ctx context.Context, name string) (sqlc.Role, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindRoleByName(ctx, name)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) FindUser(ctx context.Context, id string) (sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.FindUser(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) IncrementNotificationCounter(ctx context.Context, recipientID string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.IncrementNotificationCounter(ctx, recipientID)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) InsertAudit(ctx context.Context, arg sqlc.InsertAuditParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.InsertAudit(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) ListOwnNotifications(ctx context.Context, arg sqlc.ListOwnNotificationsParams) ([]sqlc.Notification, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ListOwnNotifications(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ListPermissions(ctx context.Context) ([]sqlc.Permission, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ListPermissions(ctx)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ListRolePermissionIDs(ctx context.Context, roleID string) ([]string, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ListRolePermissionIDs(ctx, roleID)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ListRolePermissions(ctx context.Context, roleID string) ([]sqlc.ListRolePermissionsRow, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ListRolePermissions(ctx, roleID)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ListRoles(ctx context.Context) ([]sqlc.Role, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ListRoles(ctx)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ListUsers(ctx context.Context, arg sqlc.ListUsersParams) ([]sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.ListUsers(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LockEmail(ctx context.Context, id string) (sqlc.EmailJob, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LockEmail(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LockOwnNotification(ctx context.Context, arg sqlc.LockOwnNotificationParams) (sqlc.Notification, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LockOwnNotification(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LockPermission(ctx context.Context, id string) (sqlc.Permission, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LockPermission(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LockRefreshFamily(ctx context.Context, id string) (sqlc.RefreshFamily, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LockRefreshFamily(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LockRole(ctx context.Context, id string) (sqlc.Role, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LockRole(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LockUser(ctx context.Context, id string) (sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LockUser(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) LookupAuthRefreshToken(ctx context.Context, tokenHash []byte) (sqlc.AuthRefreshToken, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.LookupAuthRefreshToken(ctx, tokenHash)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) NotificationBacklog(ctx context.Context, arg sqlc.NotificationBacklogParams) ([]sqlc.Notification, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.NotificationBacklog(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) NotificationCursor(ctx context.Context, arg sqlc.NotificationCursorParams) (int64, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.NotificationCursor(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) NotificationPage(ctx context.Context, arg sqlc.NotificationPageParams) ([]sqlc.Notification, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.NotificationPage(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) NotificationSequence(ctx context.Context, recipientID string) (int64, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.NotificationSequence(ctx, recipientID)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) ReadNotification(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.ReadNotification(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) RenewEmail(ctx context.Context, arg sqlc.RenewEmailParams) (int64, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.RenewEmail(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) RevokeAuthRefreshFamily(ctx context.Context, familyID string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.RevokeAuthRefreshFamily(ctx, familyID)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) RevokeAuthRefreshToken(ctx context.Context, id string) (int64, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.RevokeAuthRefreshToken(ctx, id)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) RevokeRefreshFamilyRecord(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.RevokeRefreshFamilyRecord(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) SeedAdminPermissions(ctx context.Context) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.SeedAdminPermissions(ctx)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) SeedPermission(ctx context.Context, name string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.SeedPermission(ctx, name)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) SeedRole(ctx context.Context, name string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.SeedRole(ctx, name)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) SeedUser(ctx context.Context, arg sqlc.SeedUserParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.SeedUser(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) SetNotificationEmailStatus(ctx context.Context, arg sqlc.SetNotificationEmailStatusParams) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.SetNotificationEmailStatus(ctx, arg)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) SoftDeleteUser(ctx context.Context, id string) error {
	ctx, span := telemetry.Start(ctx, "database")
	r0 := t.q.SoftDeleteUser(ctx, id)
	telemetry.Finish(span, r0)
	return r0
}
func (t *tracedQueries) UpdatePermission(ctx context.Context, arg sqlc.UpdatePermissionParams) (sqlc.Permission, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.UpdatePermission(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) UpdateRole(ctx context.Context, arg sqlc.UpdateRoleParams) (sqlc.Role, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.UpdateRole(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) UpdateUser(ctx context.Context, arg sqlc.UpdateUserParams) (sqlc.User, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.UpdateUser(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
func (t *tracedQueries) UserHasPermission(ctx context.Context, arg sqlc.UserHasPermissionParams) (bool, error) {
	ctx, span := telemetry.Start(ctx, "database")
	r0, r1 := t.q.UserHasPermission(ctx, arg)
	telemetry.Finish(span, r1)
	return r0, r1
}
